<?php
	define("APP_CONSUMER_KEY", "YOUR_APP_CONSUMER_KEY");
	define("APP_CONSUMER_SECRET", "YOUR_APP_CONSUMER_SECRET");
	define("APP_OAUTH_TOKEN", "YOUR_APP_OAUTH_TOKEN");
	define("APP_OAUTH_SECRET", "YOUR_APP_OAUTH_SECRET");
?>