<?php

define("YOUR_TWITTER_APP_CONSUMER_KEY", "YOUR_TWITTER_APP_CONSUMER_KEY_HERE");
define("YOUR_TWITTER_APP_CONSUMER_SECRET", "YOUR_TWITTER_APP_CONSUMER_SECRET_HERE");
define("YOUR_TWITTER_APP_OAUTH_TOKEN", "YOUR_TWITTER_APP_OAUTH_TOKEN_HERE");
define("YOUR_TWITTER_APP_OAUTH_SECRET", "YOUR_TWITTER_APP_OAUTH_SECRET_HERE");

?>